### ISSUE TITLE
Добавить Возможность смены языка

### ISSUE THREAD

**Issue by antonhoang** [Valter4578/bonsai.#164]

**Comment by VladimirBrejcha** [comment]
В принципе возможность и так есть со сменой языка устройства, так работает в большей части приложений, я бы рекомендовал пока забить так как кейс странный (приложение на одном языке а система на другом)

**Comment by antonhoang** [comment]
Имплементировать ЮАЙ экрана выбора языка, 
так же показать в самый первый раз при перед онбордингом 
разместить на экране настроек
