### ISSUE TITLE
Изменить цвет категорий на градиент 

### ISSUE THREAD

**Issue by Valter4578** [Valter4578/bonsai.#52]
Сейчас в приложении категории отображаются одним цветом(иконки, текст). Нужно переработать, чтобы категории использовали не один цвет, а градиент

**Comment by VladimirBrejcha** [comment]
Hi everyone. I have prepared a few new gradients to total of 9

Hope you like them

<img width="300" alt="image" src="https://user-images.githubusercontent.com/44097057/184522901-4f0abf41-a676-4e0d-bf26-2b579687a95b.png">
